# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-Translation
version:      0.17
version_from: lib/Apache2/Translation.pm
installdirs:  site
requires:
    Apache2::ModSSL:               0
    Class::Member:                 1.3
    DBI:                           0
    mod_perl2:                     0
    Perl::AtEndOfScope:            0
    Template:                      2.15
    Test::Deep:                    0
    Tie::Cache::LRU:               0.21
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
